/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mercadollars;

import Recursos_form.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * Interfaz: ÓscarMaqueda
 * Logica: ÓscarMaqueda
 */
public class PlantillaEnlaces extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlantillaEnlaces.class.getName());

    /**
     * Creates new form PlantillaEnlaces
     */
    private final Color verdeClaro = new Color(204, 255, 204);
    private final Color verdeOscuro = new Color(0, 204, 51);
    static public boolean semaforo = true;
    static public JPanel panelOG;

    public PlantillaEnlaces() {
        //INICIAR COMPONENTES Y PONER FULLSCREEN
        this.setUndecorated(true);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //-----------------------------------------
    }

    public PlantillaEnlaces(String ventana, javax.swing.JPanel panel, boolean admin) {
        //INICIAR COMPONENTES Y PONER FULLSCREEN
        this.setUndecorated(true);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        boolean tipoUsuario = admin;
        //-----------------------------------------
        if (!admin) {
            //btnEmpleados.setEnabled(false);
            //btnProveedores.setEnabled(false);
            //btnPromociones.setEnabled(false);
            jPanel1.remove(btnEmpleados);
            jPanel1.remove(btnProveedores);
            jPanel1.remove(btnPromociones);
            this.revalidate();
            this.repaint();
        }
        btnUsuario.setFocusable(false); //EVITAR EL SELECCIONADO POR DEFECTO DEL USUARIO
        panelOG = panel;
        cambiarHeader(ventana);
        cambiarVentana();
    }

    public PlantillaEnlaces(String ventana) {
        //INICIAR COMPONENTES Y PONER FULLSCREEN
        this.setUndecorated(true);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //-----------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlHipervinculo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnPromociones = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMercaDollars = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlHipervinculo.setBackground(new java.awt.Color(255, 255, 255));
        pnlHipervinculo.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes);

        btnEmpleados.setBackground(new java.awt.Color(204, 255, 204));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados);

        btnProductos.setBackground(new java.awt.Color(204, 255, 204));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos);

        btnVentas.setBackground(new java.awt.Color(204, 255, 204));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas);

        btnProveedores.setBackground(new java.awt.Color(204, 255, 204));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedores);

        btnPedidos.setBackground(new java.awt.Color(204, 255, 204));
        btnPedidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPedidos);

        btnPromociones.setBackground(new java.awt.Color(204, 255, 204));
        btnPromociones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPromociones.setText("Promociones");
        btnPromociones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 0, 0)));
        btnPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPromociones);

        btnFacturacion.setBackground(new java.awt.Color(204, 255, 204));
        btnFacturacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFacturacion.setText("Facturación");
        btnFacturacion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacturacion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        pnlHipervinculo.add(jPanel1, gridBagConstraints);

        btnUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(51, 153, 0));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setBorder(null);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
        pnlHipervinculo.add(btnUsuario, gridBagConstraints);

        pnlTitulo.setBackground(new java.awt.Color(0, 204, 51));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 204, 51));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Titulo de la ventana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 0);
        pnlTitulo.add(lblTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlHipervinculo.add(pnlTitulo, gridBagConstraints);

        lblMercaDollars.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        lblMercaDollars.setForeground(new java.awt.Color(0, 204, 51));
        lblMercaDollars.setText("MercaDollars");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlHipervinculo.add(lblMercaDollars, gridBagConstraints);

        pnlPrincipal.add(pnlHipervinculo, java.awt.BorderLayout.PAGE_START);

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setLayout(new java.awt.GridBagLayout());
        pnlPrincipal.add(pnlInfo, java.awt.BorderLayout.CENTER);

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));
        pnlSalir.setLayout(new java.awt.GridBagLayout());

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 153, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        btnSalir.setContentAreaFilled(false);
        btnSalir.setMaximumSize(new java.awt.Dimension(47, 34));
        btnSalir.setMinimumSize(new java.awt.Dimension(47, 34));
        btnSalir.setPreferredSize(new java.awt.Dimension(47, 34));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 25, 75);
        pnlSalir.add(btnSalir, gridBagConstraints);

        pnlPrincipal.add(pnlSalir, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarVentana() {
        pnlInfo.removeAll();
        pnlInfo.add(panelOG);
        pnlInfo.revalidate();
        pnlInfo.repaint();
        semaforo = true;
    }


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (!semaforo) {
            cambiarVentana();
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        panelOG = new Cliente();
        cambiarVentana();
        cambiarHeader("clientes");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        panelOG = new Empleados();
        cambiarVentana();
        cambiarHeader("empleados");
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        panelOG = new Productos();
        cambiarVentana();
        cambiarHeader("inventario");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        panelOG = new Ventas();
        cambiarVentana();
        cambiarHeader("caja");
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        panelOG = new Pedido();
        cambiarVentana();
        cambiarHeader("pedidos");
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        panelOG = new Proveedores();
        cambiarVentana();
        cambiarHeader("proveedores");
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionesActionPerformed
        panelOG = new Promociones();
        cambiarVentana();
        cambiarHeader("promociones");
    }//GEN-LAST:event_btnPromocionesActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        panelOG = new Facturacion();
        cambiarVentana();
        cambiarHeader("facturacion");
    }//GEN-LAST:event_btnFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlantillaEnlaces().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnPromociones;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMercaDollars;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlHipervinculo;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables

    private void cambiarHeader(String ventana) {
        quitarColor();

        switch (ventana) {
            case "clientes":
                lblTitulo.setText("Gestión de clientes");
                btnClientes.setBackground(verdeOscuro);
                break;

            case "empleados":
                lblTitulo.setText("Gestión de empleados");
                btnEmpleados.setBackground(verdeOscuro);
                break;

            case "inventario":
                lblTitulo.setText("Gestión de productos, inventario y stock");
                btnProductos.setBackground(verdeOscuro);
                break;

            case "caja":
                lblTitulo.setText("Caja/Ventas (por implementar)");
                btnVentas.setBackground(verdeOscuro);
                break;

            case "proveedores":
                lblTitulo.setText("Gestión de proveedores");
                btnProveedores.setBackground(verdeOscuro);
                break;

            case "pedidos":
                lblTitulo.setText("Gestión de pedidos");
                btnPedidos.setBackground(verdeOscuro);
                break;

            case "promociones":
                lblTitulo.setText("Gestión de promociones (por implementar)");
                btnPromociones.setBackground(verdeOscuro);
                break;

            case "facturacion":
                lblTitulo.setText("Facturación (por implementar)");
                btnFacturacion.setBackground(verdeOscuro);
                break;

            default:
                break;
        }
    }

    private void quitarColor() {
        btnFacturacion.setBackground(verdeClaro);
        btnClientes.setBackground(verdeClaro);
        btnEmpleados.setBackground(verdeClaro);
        btnPedidos.setBackground(verdeClaro);
        btnProductos.setBackground(verdeClaro);
        btnPromociones.setBackground(verdeClaro);
        btnProveedores.setBackground(verdeClaro);
        btnVentas.setBackground(verdeClaro);
    }
}
