/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author MEDAC
 */
public class Campo_form extends javax.swing.JPanel {

    /**
     * Creates new form Nombre_form
     */
    public Campo_form() {
        initComponents();
    }

    public Campo_form(JLabel jlb_Titulo, JTextField jtf_Texto) {
        this.jlb_Titulo = jlb_Titulo;
        this.jtf_Texto = jtf_Texto;
    }

    public void setJlb_Titulo(String texto) {
        this.jlb_Titulo.setText(texto);
    }

    public void setJtf_Texto(String texto) {
        this.jtf_Texto.setText(texto);
    }

    public JLabel getJlb_Titulo() {
        return jlb_Titulo;
    }

    public JTextField getJtf_Texto() {
        return jtf_Texto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Titulo = new javax.swing.JLabel();
        jtf_Texto = new javax.swing.JTextField();

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        jlb_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb_Titulo.setText("Nombre:");
        jlb_Titulo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jlb_Titulo.setMinimumSize(new java.awt.Dimension(60, 20));
        jlb_Titulo.setPreferredSize(new java.awt.Dimension(60, 20));
        add(jlb_Titulo);

        jtf_Texto.setToolTipText("");
        jtf_Texto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtf_Texto.setMinimumSize(new java.awt.Dimension(60, 20));
        jtf_Texto.setPreferredSize(new java.awt.Dimension(160, 20));
        add(jtf_Texto);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_Titulo;
    private javax.swing.JTextField jtf_Texto;
    // End of variables declaration//GEN-END:variables
}
