/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author MEDAC
 */
public class Campo_form extends javax.swing.JPanel {

    /**
     * Creates new form Nombre_form
     */
    public Campo_form() {
        initComponents();
    }

    public Campo_form(JLabel jlb_Titulo, JTextField jtf_Texto) {
        this.jlb_Titulo = jlb_Titulo;
        this.jtf_Texto = jtf_Texto;
    }

    public void setJlb_Titulo(String texto) {
        this.jlb_Titulo.setText(texto);
    }

    public void setJtf_Texto(String texto) {
        this.jtf_Texto.setText(texto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlb_Titulo = new javax.swing.JLabel();
        jtf_Texto = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jlb_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb_Titulo.setText("Nombre :");
        jlb_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlb_Titulo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jlb_Titulo.setMinimumSize(new java.awt.Dimension(60, 20));
        jlb_Titulo.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jlb_Titulo, gridBagConstraints);
        jlb_Titulo.getAccessibleContext().setAccessibleName("Nombre :");

        jtf_Texto.setToolTipText("");
        jtf_Texto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtf_Texto.setMinimumSize(new java.awt.Dimension(60, 20));
        jtf_Texto.setPreferredSize(new java.awt.Dimension(200, 20));
        jtf_Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TextoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        add(jtf_Texto, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TextoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_Titulo;
    private javax.swing.JTextField jtf_Texto;
    // End of variables declaration//GEN-END:variables
}
