/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.PlantillaEnlaces;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author MEDAC
 */
public class Cliente_form extends javax.swing.JPanel {

    /**
     * Creates new form Cliente_form
     */
    public Cliente_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dni_form = new Recursos_form.Campo_form();
        telef_form = new Recursos_form.Campo_form();
        fech_nac_form = new Recursos_form.Campo_form();
        nombre_form = new Recursos_form.Campo_form();
        btnRegistrar = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);

        dni_form.setJlb_Titulo("DNI :");
        dni_form.setJtf_Texto("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(dni_form, gridBagConstraints);

        telef_form.setJlb_Titulo("Teléfono :");
        telef_form.setJtf_Texto("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(telef_form, gridBagConstraints);

        fech_nac_form.setJlb_Titulo("Fecha de nacimiento :");
        fech_nac_form.setJtf_Texto("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(fech_nac_form, gridBagConstraints);

        nombre_form.setJlb_Titulo("Nombre :");
        nombre_form.setJtf_Texto("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(nombre_form, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setAlignmentY(0.0F);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setIconTextGap(0);
        btnRegistrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRegistrar.setMaximumSize(new java.awt.Dimension(80, 55));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(80, 55));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(60, 30));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        add(btnRegistrar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        PlantillaEnlaces pe1 = new PlantillaEnlaces("clientes");
        pe1.setLocationRelativeTo(null);
        pe1.setVisible(true);
        pe1.setResizable(false);
        pe1.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private Recursos_form.Campo_form dni_form;
    private Recursos_form.Campo_form fech_nac_form;
    private Recursos_form.Campo_form nombre_form;
    private Recursos_form.Campo_form telef_form;
    // End of variables declaration//GEN-END:variables
}
