/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author MEDAC
 */
public class Cliente extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnClienteAlta = new javax.swing.JButton();
        btnClienteModificar = new javax.swing.JButton();
        btnClienteListado = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnClienteAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnClienteAlta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnClienteAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteAlta.setText("Alta de cliente");
        btnClienteAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnClienteAlta, gridBagConstraints);

        btnClienteModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnClienteModificar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnClienteModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteModificar.setText("Modificar un cliente");
        btnClienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnClienteModificar, gridBagConstraints);

        btnClienteListado.setBackground(new java.awt.Color(0, 102, 102));
        btnClienteListado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnClienteListado.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteListado.setText("Generar listado de clientes");
        btnClienteListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteListadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnClienteListado, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteAltaActionPerformed

    private void btnClienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteModificarActionPerformed

    private void btnClienteListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteListadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAlta;
    private javax.swing.JButton btnClienteListado;
    private javax.swing.JButton btnClienteModificar;
    // End of variables declaration//GEN-END:variables
}
