/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import ClasesDAO.UsuarioDAO;
import Modelos.EmpleadoM;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;

/**
 *
 * @author ÓscarMaqueda
 */
public class EmpleadosAlta extends javax.swing.JPanel {

     /**
     * Creates new form EmpleadosAlta
     */
    private UsuarioDAO usuarioDAO;
    public EmpleadosAlta() {
        usuarioDAO = new UsuarioDAO();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        lblContrasenia2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        pwdContrasenia = new javax.swing.JPasswordField();
        pwdContrasenia2 = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblNombre, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblApellidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblApellidos, gridBagConstraints);

        lblDni.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDni.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDni.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblDni, gridBagConstraints);

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCorreo.setText("Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblCorreo, gridBagConstraints);

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelefono.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblTelefono, gridBagConstraints);

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContrasenia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContrasenia.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblContrasenia, gridBagConstraints);

        lblContrasenia2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContrasenia2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContrasenia2.setText("Repetir contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblContrasenia2, gridBagConstraints);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(300, 38));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtNombre, gridBagConstraints);

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtApellidos, gridBagConstraints);

        txtDni.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtDni, gridBagConstraints);

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtCorreo, gridBagConstraints);

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtTelefono, gridBagConstraints);

        pwdContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(pwdContrasenia, gridBagConstraints);

        pwdContrasenia2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pwdContrasenia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContrasenia2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(pwdContrasenia2, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(btnRegistrar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    private void limpiarFormulario() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDni.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        pwdContrasenia.setText("");
        pwdContrasenia2.setText("");
    }

    // Método para validar formato de DNI (8 números y 1 letra)
    private boolean validarDNI(String dni) {
        // Expresión regular para DNI español: 8 dígitos seguidos de una letra
        return dni.matches("^[0-9]{8}[A-Za-z]$");
    }

    // Método para validar formato de email
    private boolean validarEmail(String email) {
        // Expresión regular básica para email
        return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    private void registrarEmpleado() {
        
        // Obtener datos del formulario
        String nombre = txtNombre.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String dni = txtDni.getText().trim();
        String correo = txtCorreo.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String contrasenia = new String(pwdContrasenia.getPassword());
        String contrasenia2 = new String(pwdContrasenia2.getPassword());

        // Validaciones
        if (nombre.isEmpty() || correo.isEmpty() || contrasenia.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete los campos obligatorios:\n- Nombre\n- Correo\n- Contraseña",
                    "Campos Obligatorios",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!contrasenia.equals(contrasenia2)) {
            JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden",
                    "Error de Contraseña",
                    JOptionPane.ERROR_MESSAGE);
            pwdContrasenia.setText("");
            pwdContrasenia2.setText("");
            pwdContrasenia.requestFocus();
            return;
        }

        if (contrasenia.length() < 5) {
            JOptionPane.showMessageDialog(this,
                    "La contraseña debe tener al menos 5 caracteres",
                    "Contraseña Débil",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar formato de DNI (opcional)
        if (!dni.isEmpty() && !validarDNI(dni)) {
            JOptionPane.showMessageDialog(this,
                    "El formato del DNI no es válido",
                    "DNI Inválido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de email
        if (!validarEmail(correo)) {
            JOptionPane.showMessageDialog(this,
                    "El formato del correo electrónico no es válido",
                    "Email Inválido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si el DNI ya existe (solo si se proporcionó)
        if (!dni.isEmpty() && usuarioDAO.existeDNI(dni)) {
            JOptionPane.showMessageDialog(this,
                    "El DNI ya está registrado en el sistema",
                    "DNI Duplicado",
                    JOptionPane.ERROR_MESSAGE);
            txtDni.requestFocus();
            return;
        }

        // Verificar si el Email ya existe
        if (usuarioDAO.existeEmail(correo)) {
            JOptionPane.showMessageDialog(this,
                    "El correo electrónico ya está registrado en el sistema",
                    "Email Duplicado",
                    JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
            return;
        }

        // Crear objeto EmpleadoM
        EmpleadoM nuevoEmpleado = new EmpleadoM(
                nombre,
                apellidos.isEmpty() ? null : apellidos,
                dni.isEmpty() ? null : dni,
                contrasenia,
                correo,
                telefono.isEmpty() ? null : telefono,
                null // Admin será "NO" por defecto
        );

        // Registrar en la base de datos
        boolean registrado = usuarioDAO.registrarEmpleado(nuevoEmpleado);

        if (registrado) {
            JOptionPane.showMessageDialog(this,
                    "Empleado registrado exitosamente",
                    "Registro Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar el empleado.\nPor favor, intente nuevamente.",
                    "Error de Registro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarEmpleado();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void pwdContrasenia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContrasenia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdContrasenia2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblContrasenia2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JPasswordField pwdContrasenia2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
