/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class Facturacion extends javax.swing.JPanel {

    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGenerarResumenCajaDiaria = new javax.swing.JButton();
        btnConsultarVentasPorFecha = new javax.swing.JButton();
        btnListadoProductosMasVendidos = new javax.swing.JButton();
        btnConsultarClientesMasGastan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnGenerarResumenCajaDiaria.setBackground(new java.awt.Color(0, 102, 102));
        btnGenerarResumenCajaDiaria.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGenerarResumenCajaDiaria.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarResumenCajaDiaria.setText("Generar resumen de caja diaria");
        btnGenerarResumenCajaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarResumenCajaDiariaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnGenerarResumenCajaDiaria, gridBagConstraints);

        btnConsultarVentasPorFecha.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultarVentasPorFecha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnConsultarVentasPorFecha.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarVentasPorFecha.setText("Consultar ventas por fechas");
        btnConsultarVentasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVentasPorFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnConsultarVentasPorFecha, gridBagConstraints);

        btnListadoProductosMasVendidos.setBackground(new java.awt.Color(0, 102, 102));
        btnListadoProductosMasVendidos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnListadoProductosMasVendidos.setForeground(new java.awt.Color(255, 255, 255));
        btnListadoProductosMasVendidos.setText("Listado productos más vendidos del día");
        btnListadoProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoProductosMasVendidosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnListadoProductosMasVendidos, gridBagConstraints);

        btnConsultarClientesMasGastan.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultarClientesMasGastan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnConsultarClientesMasGastan.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarClientesMasGastan.setText("Consultar clientes que más gastan");
        btnConsultarClientesMasGastan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesMasGastanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnConsultarClientesMasGastan, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarResumenCajaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarResumenCajaDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarResumenCajaDiariaActionPerformed

    private void btnConsultarVentasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVentasPorFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarVentasPorFechaActionPerformed

    private void btnListadoProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoProductosMasVendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListadoProductosMasVendidosActionPerformed

    private void btnConsultarClientesMasGastanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesMasGastanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarClientesMasGastanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarClientesMasGastan;
    private javax.swing.JButton btnConsultarVentasPorFecha;
    private javax.swing.JButton btnGenerarResumenCajaDiaria;
    private javax.swing.JButton btnListadoProductosMasVendidos;
    // End of variables declaration//GEN-END:variables
}
