/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Pablo Alarcón Pérez
 */
public class ListaProductosBajoStock extends javax.swing.JPanel {

    /**
     * Creates new form ListaProductos
     */
    public ListaProductosBajoStock() {
        initComponents();
        scrollPanelProductos.getVerticalScrollBar().setUnitIncrement(13);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelProductos = new javax.swing.JScrollPane();
        pnlCapsulaProductos = new javax.swing.JPanel();
        componenteProducto1 = new Recursos_form.ComponenteProducto();
        componenteProducto2 = new Recursos_form.ComponenteProducto();
        componenteProducto3 = new Recursos_form.ComponenteProducto();
        componenteProducto4 = new Recursos_form.ComponenteProducto();
        componenteProducto5 = new Recursos_form.ComponenteProducto();
        componenteProducto6 = new Recursos_form.ComponenteProducto();
        componenteProducto7 = new Recursos_form.ComponenteProducto();
        componenteProducto8 = new Recursos_form.ComponenteProducto();
        componenteProducto9 = new Recursos_form.ComponenteProducto();
        componenteProducto10 = new Recursos_form.ComponenteProducto();
        componenteProducto11 = new Recursos_form.ComponenteProducto();
        componenteProducto12 = new Recursos_form.ComponenteProducto();
        componenteProducto13 = new Recursos_form.ComponenteProducto();
        componenteProducto14 = new Recursos_form.ComponenteProducto();
        componenteProducto15 = new Recursos_form.ComponenteProducto();
        componenteProducto16 = new Recursos_form.ComponenteProducto();
        componenteProducto17 = new Recursos_form.ComponenteProducto();
        componenteProducto18 = new Recursos_form.ComponenteProducto();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1500, 99999999));
        setMinimumSize(new java.awt.Dimension(1500, 550));
        setPreferredSize(new java.awt.Dimension(1500, 820));

        scrollPanelProductos.setBorder(null);
        scrollPanelProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelProductos.setMaximumSize(new java.awt.Dimension(1500, 9999999));
        scrollPanelProductos.setMinimumSize(new java.awt.Dimension(1500, 550));
        scrollPanelProductos.setName(""); // NOI18N
        scrollPanelProductos.setPreferredSize(new java.awt.Dimension(1500, 820));

        pnlCapsulaProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlCapsulaProductos.setMaximumSize(new java.awt.Dimension(1250, 999999));
        pnlCapsulaProductos.setMinimumSize(new java.awt.Dimension(1250, 820));
        pnlCapsulaProductos.setPreferredSize(new java.awt.Dimension(1200, 820));
        pnlCapsulaProductos.setRequestFocusEnabled(false);
        pnlCapsulaProductos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        componenteProducto1.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/agua.png"))); // NOI18N
        componenteProducto1.setInheritsPopupMenu(true);
        componenteProducto1.setLblDescrip("0.75 Euros/Litro");
        componenteProducto1.setLblNombreProducto("Botella Agua 1.5L");
        pnlCapsulaProductos.add(componenteProducto1);

        componenteProducto2.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/cola.png"))); // NOI18N
        componenteProducto2.setLblDescrip("1.20 Euros/Ud.");
        componenteProducto2.setLblNombreProducto("Coca-Cola");
        pnlCapsulaProductos.add(componenteProducto2);

        componenteProducto3.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/carne.png"))); // NOI18N
        componenteProducto3.setLblDescrip("6 Euros/Kg");
        componenteProducto3.setLblNombreProducto("Secreto Ibérico");
        pnlCapsulaProductos.add(componenteProducto3);

        componenteProducto4.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pasta.png"))); // NOI18N
        componenteProducto4.setLblDescrip("0.38 Euros/Kg");
        componenteProducto4.setLblNombreProducto("Pasta Integral");
        pnlCapsulaProductos.add(componenteProducto4);

        componenteProducto5.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pescado.png"))); // NOI18N
        componenteProducto5.setLblDescrip("5.6 Euros/Kg");
        componenteProducto5.setLblNombreProducto("Sardinas");
        pnlCapsulaProductos.add(componenteProducto5);

        componenteProducto6.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/uva.png"))); // NOI18N
        componenteProducto6.setLblDescrip("3 Euros/Kg");
        componenteProducto6.setLblNombreProducto("Uvas");
        pnlCapsulaProductos.add(componenteProducto6);

        componenteProducto7.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/agua.png"))); // NOI18N
        componenteProducto7.setInheritsPopupMenu(true);
        componenteProducto7.setLblDescrip("0.75 Euros/Litro");
        componenteProducto7.setLblNombreProducto("Botella Agua 1.5L");
        pnlCapsulaProductos.add(componenteProducto7);

        componenteProducto8.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/cola.png"))); // NOI18N
        componenteProducto8.setLblDescrip("1.20 Euros/Ud.");
        componenteProducto8.setLblNombreProducto("Coca-Cola");
        pnlCapsulaProductos.add(componenteProducto8);

        componenteProducto9.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/carne.png"))); // NOI18N
        componenteProducto9.setLblDescrip("6 Euros/Kg");
        componenteProducto9.setLblNombreProducto("Secreto Ibérico");
        pnlCapsulaProductos.add(componenteProducto9);

        componenteProducto10.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pasta.png"))); // NOI18N
        componenteProducto10.setLblDescrip("0.38 Euros/Kg");
        componenteProducto10.setLblNombreProducto("Pasta Integral");
        pnlCapsulaProductos.add(componenteProducto10);

        componenteProducto11.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pescado.png"))); // NOI18N
        componenteProducto11.setLblDescrip("5.6 Euros/Kg");
        componenteProducto11.setLblNombreProducto("Sardinas");
        pnlCapsulaProductos.add(componenteProducto11);

        componenteProducto12.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/uva.png"))); // NOI18N
        componenteProducto12.setLblDescrip("3 Euros/Kg");
        componenteProducto12.setLblNombreProducto("Uvas");
        pnlCapsulaProductos.add(componenteProducto12);

        componenteProducto13.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/agua.png"))); // NOI18N
        componenteProducto13.setInheritsPopupMenu(true);
        componenteProducto13.setLblDescrip("0.75 Euros/Litro");
        componenteProducto13.setLblNombreProducto("Botella Agua 1.5L");
        pnlCapsulaProductos.add(componenteProducto13);

        componenteProducto14.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/cola.png"))); // NOI18N
        componenteProducto14.setLblDescrip("1.20 Euros/Ud.");
        componenteProducto14.setLblNombreProducto("Coca-Cola");
        pnlCapsulaProductos.add(componenteProducto14);

        componenteProducto15.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/carne.png"))); // NOI18N
        componenteProducto15.setLblDescrip("6 Euros/Kg");
        componenteProducto15.setLblNombreProducto("Secreto Ibérico");
        pnlCapsulaProductos.add(componenteProducto15);

        componenteProducto16.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pasta.png"))); // NOI18N
        componenteProducto16.setLblDescrip("0.38 Euros/Kg");
        componenteProducto16.setLblNombreProducto("Pasta Integral");
        pnlCapsulaProductos.add(componenteProducto16);

        componenteProducto17.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/pescado.png"))); // NOI18N
        componenteProducto17.setLblDescrip("5.6 Euros/Kg");
        componenteProducto17.setLblNombreProducto("Sardinas");
        pnlCapsulaProductos.add(componenteProducto17);

        componenteProducto18.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/uva.png"))); // NOI18N
        componenteProducto18.setLblDescrip("3 Euros/Kg");
        componenteProducto18.setLblNombreProducto("Uvas");
        pnlCapsulaProductos.add(componenteProducto18);

        scrollPanelProductos.setViewportView(pnlCapsulaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Recursos_form.ComponenteProducto componenteProducto1;
    private Recursos_form.ComponenteProducto componenteProducto10;
    private Recursos_form.ComponenteProducto componenteProducto11;
    private Recursos_form.ComponenteProducto componenteProducto12;
    private Recursos_form.ComponenteProducto componenteProducto13;
    private Recursos_form.ComponenteProducto componenteProducto14;
    private Recursos_form.ComponenteProducto componenteProducto15;
    private Recursos_form.ComponenteProducto componenteProducto16;
    private Recursos_form.ComponenteProducto componenteProducto17;
    private Recursos_form.ComponenteProducto componenteProducto18;
    private Recursos_form.ComponenteProducto componenteProducto2;
    private Recursos_form.ComponenteProducto componenteProducto3;
    private Recursos_form.ComponenteProducto componenteProducto4;
    private Recursos_form.ComponenteProducto componenteProducto5;
    private Recursos_form.ComponenteProducto componenteProducto6;
    private Recursos_form.ComponenteProducto componenteProducto7;
    private Recursos_form.ComponenteProducto componenteProducto8;
    private Recursos_form.ComponenteProducto componenteProducto9;
    private javax.swing.JPanel pnlCapsulaProductos;
    private javax.swing.JScrollPane scrollPanelProductos;
    // End of variables declaration//GEN-END:variables
}
