/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author pablo
 */
public class ListaProductos extends javax.swing.JPanel {

    /**
     * Creates new form ListaProductos
     */
    public ListaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteProducto1 = new Recursos_form.ComponenteProducto();
        componenteProducto2 = new Recursos_form.ComponenteProducto();
        componenteProducto3 = new Recursos_form.ComponenteProducto();
        componenteProducto4 = new Recursos_form.ComponenteProducto();
        componenteProducto5 = new Recursos_form.ComponenteProducto();
        componenteProducto6 = new Recursos_form.ComponenteProducto();

        setMaximumSize(new java.awt.Dimension(1128, 200));
        setMinimumSize(new java.awt.Dimension(1235, 200));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1128, 200));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));

        componenteProducto1.setImgPro(new javax.swing.ImageIcon(getClass().getResource("/agua.png"))); // NOI18N
        componenteProducto1.setInheritsPopupMenu(true);
        componenteProducto1.setLblDescrip("0.75 Euros/Litro");
        componenteProducto1.setLblNombreProducto("Botella 1.5Litros");
        add(componenteProducto1);
        add(componenteProducto2);
        add(componenteProducto3);
        add(componenteProducto4);
        add(componenteProducto5);
        add(componenteProducto6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Recursos_form.ComponenteProducto componenteProducto1;
    private Recursos_form.ComponenteProducto componenteProducto2;
    private Recursos_form.ComponenteProducto componenteProducto3;
    private Recursos_form.ComponenteProducto componenteProducto4;
    private Recursos_form.ComponenteProducto componenteProducto5;
    private Recursos_form.ComponenteProducto componenteProducto6;
    // End of variables declaration//GEN-END:variables
}
