/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.PlantillaEnlaces;

/**
 *
 * @author FranciscoJavierJimenezMuñoz
 */
public class Pedido extends javax.swing.JPanel {

    /**
     * Creates new form Empleados
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnPedidoAlta = new javax.swing.JButton();
        btnPedidoModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnPedidoAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnPedidoAlta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPedidoAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidoAlta.setText("Alta de pedido");
        btnPedidoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnPedidoAlta, gridBagConstraints);

        btnPedidoModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnPedidoModificar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPedidoModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidoModificar.setText("Modificar un pedido");
        btnPedidoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnPedidoModificar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoAltaActionPerformed
        PlantillaEnlaces.semaforo = false;
        PedidoAlta PA_ventana = new PedidoAlta();
        
        this.removeAll();
        this.add(PA_ventana);
        this.revalidate();
        this.repaint();
        
        PlantillaEnlaces.panelOG = new Pedido();
    }//GEN-LAST:event_btnPedidoAltaActionPerformed

    private void btnPedidoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoModificarActionPerformed
        PlantillaEnlaces.semaforo = false;
        PedidoModificar PM_ventana = new PedidoModificar();
        
        this.removeAll();
        this.add(PM_ventana);
        this.revalidate();
        this.repaint();
        
        PlantillaEnlaces.panelOG = new Pedido();
    }//GEN-LAST:event_btnPedidoModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedidoAlta;
    private javax.swing.JButton btnPedidoModificar;
    // End of variables declaration//GEN-END:variables
}
