/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import ClasesDAO.PedidoDAO;
import Modelos.PedidoM;
import java.awt.Color;


/**
 *
 * @author ÓscarMaqueda
 */
public class PedidoModificar extends javax.swing.JPanel {

    /**
     * Creates new form Empleados
     */
    public PedidoModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblID_Proveedor = new javax.swing.JLabel();
        lblID_Producto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtID_Proveedor = new javax.swing.JTextField();
        txtID_Producto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblIdPedido = new javax.swing.JLabel();
        txtIdPedido = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblID_Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblID_Proveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblID_Proveedor.setText("ID Proveedor :");
        lblID_Proveedor.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblID_Proveedor, gridBagConstraints);

        lblID_Producto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblID_Producto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblID_Producto.setText("ID Producto :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblID_Producto, gridBagConstraints);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCantidad.setText("Cantidad :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblCantidad, gridBagConstraints);

        txtID_Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtID_Proveedor.setPreferredSize(new java.awt.Dimension(300, 38));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtID_Proveedor, gridBagConstraints);

        txtID_Producto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtID_Producto, gridBagConstraints);

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtCantidad, gridBagConstraints);

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Pedido");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 0);
        add(btnModificar, gridBagConstraints);

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(51, 153, 0));
        btnConfirmar.setText("Confirmar Pedido");
        btnConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        btnConfirmar.setPreferredSize(new java.awt.Dimension(400, 39));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(btnConfirmar, gridBagConstraints);

        lblIdPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIdPedido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblIdPedido.setText("ID Pedido:");
        lblIdPedido.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblIdPedido, gridBagConstraints);

        txtIdPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdPedido.setForeground(java.awt.Color.gray);
        txtIdPedido.setText("Coloque su ID aquí");
        txtIdPedido.setPreferredSize(new java.awt.Dimension(300, 38));
        txtIdPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdPedidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdPedidoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtIdPedido, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdPedidoFocusLost
        if (txtIdPedido.getText().isEmpty()) {
            txtIdPedido.setForeground(Color.GRAY);
            txtIdPedido.setText("Coloque su ID aquí");
        }
    }//GEN-LAST:event_txtIdPedidoFocusLost

    private void txtIdPedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdPedidoFocusGained
        if (txtIdPedido.getText().equals("Coloque su ID aquí")) {
            txtIdPedido.setText("");
            txtIdPedido.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtIdPedidoFocusGained

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String textoId = txtIdPedido.getText();
            if (textoId.equals("Coloque su ID aquí") || textoId.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduce un número de ID.");
                return;
            }

            int id = Integer.parseInt(textoId);

            ClasesDAO.PedidoDAO dao = new ClasesDAO.PedidoDAO(Util.Conexion.obtenerConexion());
            Modelos.PedidoM p = dao.buscarPorId(id);

            if (p != null) {
                txtID_Proveedor.setText(String.valueOf(p.getIdProveedor()));
                txtID_Producto.setText(String.valueOf(p.getIdEmpleado()));
                txtCantidad.setText(String.valueOf(p.getCantidad()));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Pedido no encontrado.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser un valor numérico.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            Modelos.PedidoM p = new Modelos.PedidoM();

            String idTexto = txtIdPedido.getText();
            if (idTexto.equals("Coloque su ID aquí") || idTexto.isEmpty()) {
                throw new Exception("Debe indicar un ID de pedido válido.");
            }

            p.setIdPedido(Integer.parseInt(idTexto));
            p.setIdProveedor(Integer.parseInt(txtID_Proveedor.getText()));
            p.setIdEmpleado(Integer.parseInt(txtID_Producto.getText()));
            p.setCantidad(Integer.parseInt(txtCantidad.getText()));

            ClasesDAO.PedidoDAO dao = new ClasesDAO.PedidoDAO(Util.Conexion.obtenerConexion());

            dao.actualizarPedido(p);

            javax.swing.JOptionPane.showMessageDialog(this, "Pedido actualizado correctamente.");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Asegúrese de que todos los campos sean números válidos.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblID_Producto;
    private javax.swing.JLabel lblID_Proveedor;
    private javax.swing.JLabel lblIdPedido;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtID_Producto;
    private javax.swing.JTextField txtID_Proveedor;
    private javax.swing.JTextField txtIdPedido;
    // End of variables declaration//GEN-END:variables
}
