/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import Modelos.PedidoM;

/**
 *
 * @author FranciscoJavierJimenezMuñoz
 */
public class PedidoAlta extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadosAlta
     */
    public PedidoAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblID_Proveedor = new javax.swing.JLabel();
        lblID_Producto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtID_Proveedor = new javax.swing.JTextField();
        txtID_Producto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblID_Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblID_Proveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblID_Proveedor.setText("ID Proveedor :");
        lblID_Proveedor.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblID_Proveedor, gridBagConstraints);

        lblID_Producto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblID_Producto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblID_Producto.setText("ID Producto :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblID_Producto, gridBagConstraints);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCantidad.setText("Cantidad :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(lblCantidad, gridBagConstraints);

        txtID_Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtID_Proveedor.setPreferredSize(new java.awt.Dimension(300, 38));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtID_Proveedor, gridBagConstraints);

        txtID_Producto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtID_Producto, gridBagConstraints);

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(txtCantidad, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 25, 0);
        add(btnRegistrar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            int idProv = Integer.parseInt(txtID_Proveedor.getText());
            int idEmp = Integer.parseInt(txtID_Producto.getText());
            int cantidad = Integer.parseInt(txtCantidad.getText());

            PedidoM nuevoPedido = new PedidoM(cantidad, idProv, idEmp);

            java.sql.Connection conn = Util.ConexionBD.abrirConexion();

            ClasesDAO.PedidoDAO dao = new ClasesDAO.PedidoDAO(conn);
            dao.insertarPedido(nuevoPedido);

            javax.swing.JOptionPane.showMessageDialog(this, "Pedido registrado con éxito.");

            txtID_Proveedor.setText("");
            txtID_Producto.setText("");
            txtCantidad.setText("");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduce valores numéricos válidos (IDs y cantidad).");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblID_Producto;
    private javax.swing.JLabel lblID_Proveedor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtID_Producto;
    private javax.swing.JTextField txtID_Proveedor;
    // End of variables declaration//GEN-END:variables

}
