/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import java.awt.Color;

/**
 *
 * @author MEDAC
 */
public class ProductosModificar extends javax.swing.JPanel {

    /**
     * Creates new form ProductosModificar
     */
    public ProductosModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblProductoId = new javax.swing.JLabel();
        lblProductoNombre = new javax.swing.JLabel();
        lblProductoTipo = new javax.swing.JLabel();
        lblProductoStock = new javax.swing.JLabel();
        lblProductoRatio = new javax.swing.JLabel();
        lblProductoPrecioSinIva = new javax.swing.JLabel();
        lblProductoImpuesto = new javax.swing.JLabel();
        lblProductoPrecioFinal = new javax.swing.JLabel();
        txtProductoId = new javax.swing.JTextField();
        txtProductoNombre = new javax.swing.JTextField();
        txtProductoTipo = new javax.swing.JTextField();
        txtProductoStock = new javax.swing.JTextField();
        txtProductoRatio = new javax.swing.JTextField();
        txtProductoPrecioSinIva = new javax.swing.JTextField();
        txtProductoImpuesto = new javax.swing.JTextField();
        txtProductoPrecioFinal = new javax.swing.JTextField();
        btnBaja = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtBusquedaProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlSeparadorBusqueda = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoId.setText("ID Producto:");
        lblProductoId.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoId, gridBagConstraints);

        lblProductoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoNombre.setText("Nombre:");
        lblProductoNombre.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoNombre, gridBagConstraints);

        lblProductoTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoTipo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoTipo.setText("Grupo/tipo:");
        lblProductoTipo.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoTipo, gridBagConstraints);

        lblProductoStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoStock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoStock.setText("Stock:");
        lblProductoStock.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoStock, gridBagConstraints);

        lblProductoRatio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoRatio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoRatio.setText("Ratio aviso:");
        lblProductoRatio.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoRatio, gridBagConstraints);

        lblProductoPrecioSinIva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoPrecioSinIva.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoPrecioSinIva.setText("Precio sin IVA:");
        lblProductoPrecioSinIva.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoPrecioSinIva, gridBagConstraints);

        lblProductoImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoImpuesto.setText("IVA aplicable:");
        lblProductoImpuesto.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoImpuesto, gridBagConstraints);

        lblProductoPrecioFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoPrecioFinal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoPrecioFinal.setText("Precio final:");
        lblProductoPrecioFinal.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoPrecioFinal, gridBagConstraints);

        txtProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoId, gridBagConstraints);

        txtProductoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoNombre.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoNombre, gridBagConstraints);

        txtProductoTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoTipo.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoTipo, gridBagConstraints);

        txtProductoStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoStock.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoStock, gridBagConstraints);

        txtProductoRatio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoRatio.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtProductoRatio, gridBagConstraints);

        txtProductoPrecioSinIva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoPrecioSinIva.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtProductoPrecioSinIva, gridBagConstraints);

        txtProductoImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoImpuesto.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtProductoImpuesto, gridBagConstraints);

        txtProductoPrecioFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoPrecioFinal.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtProductoPrecioFinal, gridBagConstraints);

        btnBaja.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBaja.setForeground(new java.awt.Color(51, 153, 0));
        btnBaja.setText("Dar de baja");
        btnBaja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        btnBaja.setPreferredSize(new java.awt.Dimension(400, 39));
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        add(btnBaja, gridBagConstraints);

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new java.awt.Dimension(400, 39));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnModificar, gridBagConstraints);

        txtBusquedaProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtBusquedaProducto.setPreferredSize(new java.awt.Dimension(830, 40));
        txtBusquedaProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaProductoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtBusquedaProducto, gridBagConstraints);

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(99, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(btnBuscar, gridBagConstraints);

        pnlSeparadorBusqueda.setBackground(new java.awt.Color(0, 102, 102));
        pnlSeparadorBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        pnlSeparadorBusqueda.setPreferredSize(new java.awt.Dimension(940, 1));

        javax.swing.GroupLayout pnlSeparadorBusquedaLayout = new javax.swing.GroupLayout(pnlSeparadorBusqueda);
        pnlSeparadorBusqueda.setLayout(pnlSeparadorBusquedaLayout);
        pnlSeparadorBusquedaLayout.setHorizontalGroup(
            pnlSeparadorBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlSeparadorBusquedaLayout.setVerticalGroup(
            pnlSeparadorBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(pnlSeparadorBusqueda, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBusquedaProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaProductoFocusGained
        if (txtBusquedaProducto.getText().equals("Introduce la ID o el producto a buscar")) {
            txtBusquedaProducto.setText("");
            txtBusquedaProducto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBusquedaProductoFocusGained

    private void txtBusquedaProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaProductoFocusLost
        if (txtBusquedaProducto.getText().isEmpty()) {
            txtBusquedaProducto.setForeground(Color.GRAY);
            txtBusquedaProducto.setText("Introduce la ID o el producto a buscar");
        }
    }//GEN-LAST:event_txtBusquedaProductoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblProductoId;
    private javax.swing.JLabel lblProductoImpuesto;
    private javax.swing.JLabel lblProductoNombre;
    private javax.swing.JLabel lblProductoPrecioFinal;
    private javax.swing.JLabel lblProductoPrecioSinIva;
    private javax.swing.JLabel lblProductoRatio;
    private javax.swing.JLabel lblProductoStock;
    private javax.swing.JLabel lblProductoTipo;
    private javax.swing.JPanel pnlSeparadorBusqueda;
    private javax.swing.JTextField txtBusquedaProducto;
    private javax.swing.JTextField txtProductoId;
    private javax.swing.JTextField txtProductoImpuesto;
    private javax.swing.JTextField txtProductoNombre;
    private javax.swing.JTextField txtProductoPrecioFinal;
    private javax.swing.JTextField txtProductoPrecioSinIva;
    private javax.swing.JTextField txtProductoRatio;
    private javax.swing.JTextField txtProductoStock;
    private javax.swing.JTextField txtProductoTipo;
    // End of variables declaration//GEN-END:variables
}
