/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class ProductosAlta extends javax.swing.JPanel {

    /**
     * Creates new form AltaProducto
     */
    public ProductosAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblProductoId = new javax.swing.JLabel();
        lblProductoNombre = new javax.swing.JLabel();
        lblProductoTipo = new javax.swing.JLabel();
        lblProductoStock = new javax.swing.JLabel();
        lblProductoRatio = new javax.swing.JLabel();
        lblProductoPrecioSinIva = new javax.swing.JLabel();
        lblProductoImpuesto = new javax.swing.JLabel();
        lblProductoPrecioFinal = new javax.swing.JLabel();
        txtProductoId = new javax.swing.JTextField();
        txtProductoNombre = new javax.swing.JTextField();
        txtProductoTipo = new javax.swing.JTextField();
        txtProductoStock = new javax.swing.JTextField();
        txtProductoRatio = new javax.swing.JTextField();
        txtProductoPrecioSinIva = new javax.swing.JTextField();
        txtProductoImpuesto = new javax.swing.JTextField();
        txtProductoPrecioFinal = new javax.swing.JTextField();
        btnDarAlta = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1250, 381));
        setPreferredSize(new java.awt.Dimension(1250, 381));
        setLayout(new java.awt.GridBagLayout());

        lblProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoId.setText("ID Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoId, gridBagConstraints);

        lblProductoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoNombre, gridBagConstraints);

        lblProductoTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoTipo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoTipo.setText("Grupo/tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoTipo, gridBagConstraints);

        lblProductoStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoStock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoStock.setText("Stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoStock, gridBagConstraints);

        lblProductoRatio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoRatio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoRatio.setText("Ratio aviso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoRatio, gridBagConstraints);

        lblProductoPrecioSinIva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoPrecioSinIva.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoPrecioSinIva.setText("Precio sin IVA:");
        lblProductoPrecioSinIva.setMaximumSize(new java.awt.Dimension(170, 40));
        lblProductoPrecioSinIva.setMinimumSize(new java.awt.Dimension(170, 40));
        lblProductoPrecioSinIva.setPreferredSize(new java.awt.Dimension(170, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoPrecioSinIva, gridBagConstraints);

        lblProductoImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoImpuesto.setText("IVA aplicable:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoImpuesto, gridBagConstraints);

        lblProductoPrecioFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoPrecioFinal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoPrecioFinal.setText("Precio final:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoPrecioFinal, gridBagConstraints);

        txtProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoId, gridBagConstraints);

        txtProductoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoNombre.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoNombre, gridBagConstraints);

        txtProductoTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoTipo.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoTipo, gridBagConstraints);

        txtProductoStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoStock.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoStock, gridBagConstraints);

        txtProductoRatio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoRatio.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoRatio, gridBagConstraints);

        txtProductoPrecioSinIva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoPrecioSinIva.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoPrecioSinIva, gridBagConstraints);

        txtProductoImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoImpuesto.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoImpuesto, gridBagConstraints);

        txtProductoPrecioFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoPrecioFinal.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoPrecioFinal, gridBagConstraints);

        btnDarAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnDarAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDarAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnDarAlta.setText("Dar de alta");
        btnDarAlta.setPreferredSize(new java.awt.Dimension(400, 39));
        btnDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnDarAlta, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDarAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JLabel lblProductoId;
    private javax.swing.JLabel lblProductoImpuesto;
    private javax.swing.JLabel lblProductoNombre;
    private javax.swing.JLabel lblProductoPrecioFinal;
    private javax.swing.JLabel lblProductoPrecioSinIva;
    private javax.swing.JLabel lblProductoRatio;
    private javax.swing.JLabel lblProductoStock;
    private javax.swing.JLabel lblProductoTipo;
    private javax.swing.JTextField txtProductoId;
    private javax.swing.JTextField txtProductoImpuesto;
    private javax.swing.JTextField txtProductoNombre;
    private javax.swing.JTextField txtProductoPrecioFinal;
    private javax.swing.JTextField txtProductoPrecioSinIva;
    private javax.swing.JTextField txtProductoRatio;
    private javax.swing.JTextField txtProductoStock;
    private javax.swing.JTextField txtProductoTipo;
    // End of variables declaration//GEN-END:variables
}
