/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.PlantillaEnlaces;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnProductoAlta = new javax.swing.JButton();
        btnProductoModificar = new javax.swing.JButton();
        btnProductoListado = new javax.swing.JButton();
        btnProductoListadoBajoStock = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnProductoAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnProductoAlta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProductoAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoAlta.setText("Alta de producto");
        btnProductoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProductoAlta, gridBagConstraints);

        btnProductoModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnProductoModificar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProductoModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoModificar.setText("Modificar un producto");
        btnProductoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProductoModificar, gridBagConstraints);

        btnProductoListado.setBackground(new java.awt.Color(0, 102, 102));
        btnProductoListado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProductoListado.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoListado.setText("Generar listado de productos");
        btnProductoListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoListadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProductoListado, gridBagConstraints);

        btnProductoListadoBajoStock.setBackground(new java.awt.Color(0, 102, 102));
        btnProductoListadoBajoStock.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProductoListadoBajoStock.setForeground(new java.awt.Color(255, 255, 255));
        btnProductoListadoBajoStock.setText("Generar listado de productos bajos en stock");
        btnProductoListadoBajoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoListadoBajoStockActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProductoListadoBajoStock, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoAltaActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new ProductosAlta());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Productos();
    }//GEN-LAST:event_btnProductoAltaActionPerformed

    private void btnProductoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoModificarActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new ProductosModificar());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Productos();
    }//GEN-LAST:event_btnProductoModificarActionPerformed

    private void btnProductoListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoListadoActionPerformed

    private void btnProductoListadoBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoListadoBajoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoListadoBajoStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductoAlta;
    private javax.swing.JButton btnProductoListado;
    private javax.swing.JButton btnProductoListadoBajoStock;
    private javax.swing.JButton btnProductoModificar;
    // End of variables declaration//GEN-END:variables
}
