/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.PlantillaEnlaces;

/**
 *
 * @author Carlos Duarte Ruiz y Pablo Alarcón Pérez
 */
public class Promociones extends javax.swing.JPanel {

    /**
     * Creates new form Promociones
     */
    public Promociones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnPromocionAlta = new javax.swing.JButton();
        btnPromocionModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnPromocionAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnPromocionAlta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPromocionAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnPromocionAlta.setText("Alta de promoción");
        btnPromocionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 445;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(199, 239, 0, 239);
        add(btnPromocionAlta, gridBagConstraints);

        btnPromocionModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnPromocionModificar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPromocionModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnPromocionModificar.setText("Modificar una promoción");
        btnPromocionModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 239, 200, 239);
        add(btnPromocionModificar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromocionAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionAltaActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new PromocionesAlta());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Promociones();
    }//GEN-LAST:event_btnPromocionAltaActionPerformed

    private void btnPromocionModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionModificarActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new PromocionesModificar());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Promociones();
    }//GEN-LAST:event_btnPromocionModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPromocionAlta;
    private javax.swing.JButton btnPromocionModificar;
    // End of variables declaration//GEN-END:variables
}
