/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Carlos Duarte Ruiz y Pablo Alarcón Pérez
 */
public class PromocionesAlta extends javax.swing.JPanel {

    /**
     * Creates new form PromocionesAlta
     */
    public PromocionesAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPromocionId = new javax.swing.JLabel();
        lblPromocionNombre = new javax.swing.JLabel();
        lblPromocionFechaInicio = new javax.swing.JLabel();
        lblPromocionFechaFin = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblPromocionDescripcion = new javax.swing.JLabel();
        txtPromocionId = new javax.swing.JTextField();
        txtPromocionNombre = new javax.swing.JTextField();
        txtPromocionFechaInicio = new javax.swing.JTextField();
        txtPromocionFechaFin = new javax.swing.JTextField();
        txtPromocionDescuento = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPromocionDescripcion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblPromocionId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPromocionId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPromocionId.setText("ID Promoción:");
        lblPromocionId.setMaximumSize(new java.awt.Dimension(170, 40));
        lblPromocionId.setMinimumSize(new java.awt.Dimension(170, 40));
        lblPromocionId.setPreferredSize(new java.awt.Dimension(170, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblPromocionId, gridBagConstraints);

        lblPromocionNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPromocionNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPromocionNombre.setText("Nombre:");
        lblPromocionNombre.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblPromocionNombre, gridBagConstraints);

        lblPromocionFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPromocionFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPromocionFechaInicio.setText("Fecha inicio:");
        lblPromocionFechaInicio.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblPromocionFechaInicio, gridBagConstraints);

        lblPromocionFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPromocionFechaFin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPromocionFechaFin.setText("Fecha fin:");
        lblPromocionFechaFin.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblPromocionFechaFin, gridBagConstraints);

        lblDescuento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDescuento.setText("Descuento (%):");
        lblDescuento.setMaximumSize(new java.awt.Dimension(170, 40));
        lblDescuento.setMinimumSize(new java.awt.Dimension(170, 40));
        lblDescuento.setPreferredSize(new java.awt.Dimension(170, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblDescuento, gridBagConstraints);

        lblPromocionDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPromocionDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromocionDescripcion.setText("Descripción");
        lblPromocionDescripcion.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(lblPromocionDescripcion, gridBagConstraints);

        txtPromocionId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPromocionId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtPromocionId, gridBagConstraints);

        txtPromocionNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPromocionNombre.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtPromocionNombre, gridBagConstraints);

        txtPromocionFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPromocionFechaInicio.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtPromocionFechaInicio, gridBagConstraints);

        txtPromocionFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPromocionFechaFin.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtPromocionFechaFin, gridBagConstraints);

        txtPromocionDescuento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPromocionDescuento.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(txtPromocionDescuento, gridBagConstraints);

        btnAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setText("Alta de promoción");
        btnAlta.setPreferredSize(new java.awt.Dimension(400, 39));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnAlta, gridBagConstraints);

        txtPromocionDescripcion.setColumns(20);
        txtPromocionDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtPromocionDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 25, 0);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblPromocionDescripcion;
    private javax.swing.JLabel lblPromocionFechaFin;
    private javax.swing.JLabel lblPromocionFechaInicio;
    private javax.swing.JLabel lblPromocionId;
    private javax.swing.JLabel lblPromocionNombre;
    private javax.swing.JTextArea txtPromocionDescripcion;
    private javax.swing.JTextField txtPromocionDescuento;
    private javax.swing.JTextField txtPromocionFechaFin;
    private javax.swing.JTextField txtPromocionFechaInicio;
    private javax.swing.JTextField txtPromocionId;
    private javax.swing.JTextField txtPromocionNombre;
    // End of variables declaration//GEN-END:variables
}
