/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.PlantillaEnlaces;

/**
 *
 * @author MEDAC
 */
public class Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnProveedoresAlta = new javax.swing.JButton();
        btnProveedoresModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnProveedoresAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnProveedoresAlta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProveedoresAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedoresAlta.setText("Dar de alta");
        btnProveedoresAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProveedoresAlta, gridBagConstraints);

        btnProveedoresModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnProveedoresModificar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProveedoresModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedoresModificar.setText("Modificar un proveedor");
        btnProveedoresModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnProveedoresModificar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedoresAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresAltaActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new ProveedoresAlta());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Proveedores();
    }//GEN-LAST:event_btnProveedoresAltaActionPerformed

    private void btnProveedoresModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresModificarActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new ProveedoresModificar());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Proveedores();
    }//GEN-LAST:event_btnProveedoresModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProveedoresAlta;
    private javax.swing.JButton btnProveedoresModificar;
    // End of variables declaration//GEN-END:variables
}
