/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import java.awt.Color;

/**
 *
 * @author Pablo Alarcón Pérez
 */
public class ProveedoresModificar extends javax.swing.JPanel {

    /**
     * Creates new form ProveedoresModificar
     */
    public ProveedoresModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfCif = new javax.swing.JTextField();
        txfTlf = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfProducto = new javax.swing.JTextField();
        btnResgist = new javax.swing.JButton();
        txfCifOrig = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CIF :");
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("TLF :");
        jLabel2.setPreferredSize(new java.awt.Dimension(48, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 15);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nombre :");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tipo de producto :");
        jLabel4.setPreferredSize(new java.awt.Dimension(197, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 15);
        add(jLabel4, gridBagConstraints);

        txfCif.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfCif.setMinimumSize(new java.awt.Dimension(64, 40));
        txfCif.setPreferredSize(new java.awt.Dimension(300, 38));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txfCif, gridBagConstraints);

        txfTlf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfTlf.setPreferredSize(new java.awt.Dimension(64, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(txfTlf, gridBagConstraints);

        txfNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfNombre.setPreferredSize(new java.awt.Dimension(300, 40));
        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txfNombre, gridBagConstraints);

        txfProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfProducto.setPreferredSize(new java.awt.Dimension(64, 40));
        txfProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(txfProducto, gridBagConstraints);

        btnResgist.setBackground(new java.awt.Color(0, 102, 102));
        btnResgist.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnResgist.setForeground(new java.awt.Color(255, 255, 255));
        btnResgist.setText("Registrar");
        btnResgist.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(btnResgist, gridBagConstraints);

        txfCifOrig.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfCifOrig.setForeground(new java.awt.Color(128, 128, 128));
        txfCifOrig.setText("Escribe el cif");
        txfCifOrig.setPreferredSize(new java.awt.Dimension(828, 40));
        txfCifOrig.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfCifOrigFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfCifOrigFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(txfCifOrig, gridBagConstraints);

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(99, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btnBuscar, gridBagConstraints);

        btnBaja.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBaja.setForeground(new java.awt.Color(51, 153, 0));
        btnBaja.setText("Dar de baja");
        btnBaja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        btnBaja.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(btnBaja, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void txfProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfProductoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txfCifOrigFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfCifOrigFocusGained
        if (txfCifOrig.getText().equals("Escribe el cif")) {
            txfCifOrig.setText("");
            txfCifOrig.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txfCifOrigFocusGained

    private void txfCifOrigFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfCifOrigFocusLost
        if (txfCifOrig.getText().isEmpty()) {
            txfCifOrig.setForeground(Color.GRAY);
            txfCifOrig.setText("Escribe el cif");
        }
    }//GEN-LAST:event_txfCifOrigFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnResgist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfCif;
    private javax.swing.JTextField txfCifOrig;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfProducto;
    private javax.swing.JTextField txfTlf;
    // End of variables declaration//GEN-END:variables
}
