/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

import com.mycompany.mercadollars.ConexionBD;
import com.mycompany.mercadollars.PlantillaEnlaces;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnVentaNueva = new javax.swing.JButton();
        btnInformeTodasVentas = new javax.swing.JButton();
        btnVentasDia = new javax.swing.JButton();
        btnVentasTicket = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnVentaNueva.setBackground(new java.awt.Color(0, 102, 102));
        btnVentaNueva.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentaNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaNueva.setText("Nueva venta");
        btnVentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaNuevaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(89, 286, 0, 286);
        add(btnVentaNueva, gridBagConstraints);

        btnInformeTodasVentas.setBackground(new java.awt.Color(0, 102, 102));
        btnInformeTodasVentas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnInformeTodasVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnInformeTodasVentas.setText("Informe de todas las ventas");
        btnInformeTodasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeTodasVentasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 0, 286);
        add(btnInformeTodasVentas, gridBagConstraints);

        btnVentasDia.setBackground(new java.awt.Color(0, 102, 102));
        btnVentasDia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentasDia.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasDia.setText("Informe ventas por día");
        btnVentasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasDiaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 0, 286);
        add(btnVentasDia, gridBagConstraints);

        btnVentasTicket.setBackground(new java.awt.Color(0, 102, 102));
        btnVentasTicket.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentasTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasTicket.setText("Informe ventas por ticket");
        btnVentasTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasTicketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 90, 286);
        add(btnVentasTicket, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaNuevaActionPerformed
        PlantillaEnlaces.semaforo = false;
        this.removeAll();
        this.add(new VentasNueva());
        this.revalidate();
        this.repaint();
        PlantillaEnlaces.panelOG = new Ventas();
    }//GEN-LAST:event_btnVentaNuevaActionPerformed

    private void btnInformeTodasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeTodasVentasActionPerformed
        try {
            Connection connection = ConexionBD.abrirConexion();
            InputStream informe = getClass().getResourceAsStream("/MercadollarsTotalVentas.jasper"); // nombre del informe de jaspersoft
            JasperPrint jasperPrint = JasperFillManager.fillReport(informe, null, connection);
            JasperViewer.viewReport(jasperPrint, false); // false para que no se cierre la app al cerrar el visor
            ConexionBD.cerrar(null, connection); // cerrar conexión
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInformeTodasVentasActionPerformed

    private void btnVentasTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasTicketActionPerformed
        String respuesta = JOptionPane.showInputDialog("Introduce el numero de ticket:");
        Integer numTicket = Integer.parseInt(respuesta);
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("NUMTICKET", numTicket);
        try {
            Connection connection = ConexionBD.abrirConexion();
            InputStream informe = getClass().getResourceAsStream("/MercadollarsVentasTicket.jasper"); // nombre del informe de jaspersoft
            JasperPrint jasperPrint = JasperFillManager.fillReport(informe, parametros, connection);
            JasperViewer.viewReport(jasperPrint, false); // false para que no se cierre la app al cerrar el visor
            ConexionBD.cerrar(null, connection); // cerrar conexión
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVentasTicketActionPerformed

    private void btnVentasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasDiaActionPerformed
        String respuesta = JOptionPane.showInputDialog("Introduce la fecha (AAAA-MM-DD):");
        java.sql.Date fechaSQL = java.sql.Date.valueOf(respuesta);
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("FECHA_VENTAS_JAVA", fechaSQL);
        try {
            Connection connection = ConexionBD.abrirConexion();
            InputStream informe = getClass().getResourceAsStream("/MercadollarsVentasPorFecha.jasper"); // nombre del informe de jaspersoft
            JasperPrint jasperPrint = JasperFillManager.fillReport(informe, parametros, connection);
            JasperViewer.viewReport(jasperPrint, false); // false para que no se cierre la app al cerrar el visor
            ConexionBD.cerrar(null, connection); // cerrar conexión
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVentasDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformeTodasVentas;
    private javax.swing.JButton btnVentaNueva;
    private javax.swing.JButton btnVentasDia;
    private javax.swing.JButton btnVentasTicket;
    // End of variables declaration//GEN-END:variables
}
