/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnVentaNueva = new javax.swing.JButton();
        btnVentaCalcularTotal = new javax.swing.JButton();
        btnVentaFormaPago = new javax.swing.JButton();
        btnVentaComprobante = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnVentaNueva.setBackground(new java.awt.Color(0, 102, 102));
        btnVentaNueva.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentaNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaNueva.setText("Nueva venta");
        btnVentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaNuevaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(89, 286, 0, 286);
        add(btnVentaNueva, gridBagConstraints);

        btnVentaCalcularTotal.setBackground(new java.awt.Color(0, 102, 102));
        btnVentaCalcularTotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentaCalcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaCalcularTotal.setText("Calcular total venta");
        btnVentaCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaCalcularTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 0, 286);
        add(btnVentaCalcularTotal, gridBagConstraints);

        btnVentaFormaPago.setBackground(new java.awt.Color(0, 102, 102));
        btnVentaFormaPago.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentaFormaPago.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaFormaPago.setText("Añadir forma de pago");
        btnVentaFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaFormaPagoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 0, 286);
        add(btnVentaFormaPago, gridBagConstraints);

        btnVentaComprobante.setBackground(new java.awt.Color(0, 102, 102));
        btnVentaComprobante.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnVentaComprobante.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaComprobante.setText("Generar comprobante de venta");
        btnVentaComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaComprobanteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 286, 90, 286);
        add(btnVentaComprobante, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaNuevaActionPerformed

    private void btnVentaCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaCalcularTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaCalcularTotalActionPerformed

    private void btnVentaFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaFormaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaFormaPagoActionPerformed

    private void btnVentaComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaComprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaComprobanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentaCalcularTotal;
    private javax.swing.JButton btnVentaComprobante;
    private javax.swing.JButton btnVentaFormaPago;
    private javax.swing.JButton btnVentaNueva;
    // End of variables declaration//GEN-END:variables
}
