/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Recursos_form;

/**
 *
 * @author Carlos Duarte Ruiz
 */
public class VentasNueva extends javax.swing.JPanel {

    /**
     * Creates new form AltaProducto
     */
    public VentasNueva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblVentaId = new javax.swing.JLabel();
        lblClienteId = new javax.swing.JLabel();
        lblProductoId = new javax.swing.JLabel();
        lblEmpleadoId = new javax.swing.JLabel();
        lblTicketVenta = new javax.swing.JLabel();
        txtVentaId = new javax.swing.JTextField();
        txtClienteId = new javax.swing.JTextField();
        txtProductoId = new javax.swing.JTextField();
        txtEmpleadoId = new javax.swing.JTextField();
        txtTicketVenta = new javax.swing.JTextField();
        btnDarAlta = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1250, 381));
        setPreferredSize(new java.awt.Dimension(1250, 381));
        setLayout(new java.awt.GridBagLayout());

        lblVentaId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentaId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVentaId.setText("ID Venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblVentaId, gridBagConstraints);

        lblClienteId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblClienteId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblClienteId.setText("ID Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblClienteId, gridBagConstraints);

        lblProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductoId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductoId.setText("ID Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblProductoId, gridBagConstraints);

        lblEmpleadoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmpleadoId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmpleadoId.setText("ID Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblEmpleadoId, gridBagConstraints);

        lblTicketVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTicketVenta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTicketVenta.setText("Ticket:");
        lblTicketVenta.setMaximumSize(new java.awt.Dimension(170, 40));
        lblTicketVenta.setMinimumSize(new java.awt.Dimension(170, 40));
        lblTicketVenta.setPreferredSize(new java.awt.Dimension(170, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(lblTicketVenta, gridBagConstraints);

        txtVentaId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtVentaId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtVentaId, gridBagConstraints);

        txtClienteId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtClienteId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtClienteId, gridBagConstraints);

        txtProductoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProductoId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtProductoId, gridBagConstraints);

        txtEmpleadoId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmpleadoId.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtEmpleadoId, gridBagConstraints);

        txtTicketVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTicketVenta.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        add(txtTicketVenta, gridBagConstraints);

        btnDarAlta.setBackground(new java.awt.Color(0, 102, 102));
        btnDarAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDarAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnDarAlta.setText("Nueva venta");
        btnDarAlta.setPreferredSize(new java.awt.Dimension(400, 39));
        btnDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(btnDarAlta, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed

        try {
            int idVenta = Integer.parseInt(txtVentaId.getText());
            int idCliente = Integer.parseInt(txtClienteId.getText());
            int idProducto = Integer.parseInt(txtProductoId.getText());
            int idEmpleado = Integer.parseInt(txtEmpleadoId.getText());
            int ticket = Integer.parseInt(txtTicketVenta.getText());

            // 2. Instanciamos el DAO y volcamos los datos
            ClasesDAO.VentasDAO dao = new ClasesDAO.VentasDAO();

            if (dao.realizarVenta(idVenta, idCliente, idProducto, idEmpleado, ticket)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Venta " + idVenta + " volcada con éxito.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo realizar el volcado.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Por favor, introduce los datos correctamente.");
        }


    }//GEN-LAST:event_btnDarAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblEmpleadoId;
    private javax.swing.JLabel lblProductoId;
    private javax.swing.JLabel lblTicketVenta;
    private javax.swing.JLabel lblVentaId;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtEmpleadoId;
    private javax.swing.JTextField txtProductoId;
    private javax.swing.JTextField txtTicketVenta;
    private javax.swing.JTextField txtVentaId;
    // End of variables declaration//GEN-END:variables
}
